bboard/bboard/urls.py
# D:\User\Documents\PycharmProjects\MoloshopBY\bboard\bboard\urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache

from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bboard/main/urls.py
# D:\User\Documents\PycharmProjects\MoloshopBY\bboard\main\urls.py

from django.urls import path
from .views import index
from .views import other_page
from .views import BBLoginView
from .views import profile
from .views import BBLogoutView
from .views import ChangeUserInfoView
from .views import BBPasswordChangeView
from .views import RegisterUserView, RegisterDoneView
from .views import user_activate
from .views import DeleteUserView
from .views import by_rubric

app_name = 'main'


urlpatterns = [
    path('accounts/register/activate/<str:sign>', user_activate, name='register_activate'),
    path('accounts/register/done/', RegisterDoneView.as_view(), name='register_done'),
    path('accounts/register/', RegisterUserView.as_view(), name='register'),
    path('accounts/profile/delete/', DeleteUserView.as_view(), name='profile_delete'),
    path('accounts/profile/change/', ChangeUserInfoView.as_view(), name='profile_change'),
    path('accounts/profile/', profile, name='profile'),
    path('accounts/login/', BBLoginView.as_view(), name='login'),
    path('accounts/logout/', BBLogoutView.as_view(), name='logout'),
    path('accounts/password/change/', BBPasswordChangeView.as_view(), name='password_change'),
    path('<int:pk>/', by_rubric, name='by_rubric'),
    path('<str:page>/', other_page, name='other'),
    path('', index, name='index'),
]

bboard/main/models.py
# D:\User\Documents\PycharmProjects\MoloshopBY\bboard\main\models.py

from django.db import models
from django.contrib.auth.models import AbstractUser

from .utilities import get_timestamp_path


class AdvUser(AbstractUser):
    is_activated = models.BooleanField(default=True, db_index=True, verbose_name='Прошел активацию?')
    send_messages = models.BooleanField(default=True, verbose_name='Слать оповещения о новых комментариях?')

    class Meta:
        verbose_name_plural = 'Пользователи'
        verbose_name = 'Пользователь'

    def delete(self, *args, **kwargs):
        for bb in self.bb_set.all():
            bb.delete()
        super().delete(*args, **kwargs)
    class Meta(AbstractUser.Meta):
        pass


class Rubric(models.Model):
    name = models.CharField(max_length=20, db_index=True, unique=True, verbose_name='Haзвaниe')
    order = models.SmallIntegerField(default=0, db_index=True, verbose_name='Пopядoк')
    super_rubric = models.ForeignKey('SuperRubric', on_delete=models.PROTECT, null=True, blank=True,
                                     verbose_name='Haдpyбpикa')

    class Meta:
        verbose_name_plural = 'Рубрики'
        verbose_name = 'Рубрика'


class SuperRubricManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(super_rubric__isnull=True)


class SuperRubric(Rubric):
    objects = SuperRubricManager()

    def __str__(self):
        return self.name

    class Meta:
        proxy = True
        ordering = ('order', 'name')
        verbose_name_plural = 'Надрубрики'
        verbose_name = 'Надрубрика'


class SubRubricManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(super_rubric__isnull=False)


class SubRubric(Rubric):
    objects = SubRubricManager()

    def __str__(self):
        return '%s - %s' % (self.super_rubric.name, self.name)

    class Meta:
        proxy = True
        ordering = ('super_rubric__order', 'super_rubric__name', 'order', 'name')
        verbose_name_plural = 'Подрубрики'
        verbose_name = 'Подрубрика'


class Bb(models.Model):
    rubric = models.ForeignKey(SubRubric, on_delete=models.PROTECT, verbose_name='Рубрика')
    title = models.CharField(max_length=50, verbose_name='Товар')
    content = models.TextField(verbose_name='Описание')
    price = models.FloatField(default=0, verbose_name='Цена')
    contacts = models.TextField(verbose_name='Контакты')
    image = models.ImageField(blank=True, upload_to=get_timestamp_path, verbose_name='Изображения')
    author = models.ForeignKey(AdvUser, on_delete=models.CASCADE, verbose_name='Автор объявления')
    is_active = models.BooleanField(default=True, db_index=True, verbose_name='Выводить в списке?')
    created_at = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликованно')

    def delete(self, *args, **kwargs):
        for ai in self.additionalimage_set.all():
            ai.delete()
        super().delete(*args, **kwargs)

    class Meta:
        verbose_name_plural='Объявления'
        verbose_name = 'Объявление'
        ordering = ['-created_at']


class AdditionalImage(models.Model):
    bb = models.ForeignKey(Bb, on_delete=models.CASCADE, verbose_name='Объявление')
    image = models.ImageField(upload_to=get_timestamp_path, verbose_name='Изображение')

    class Meta:
        verbose_name_plural = 'Дополнительные иллюстрации'
        verbose_name = 'Дополнительная иллюстрация'

bboard/main/forms.py
# D:\User\Documents\PycharmProjects\MoloshopBY\bboard\main\forms.py

# class ChangeUserInfoForm
from django import forms
from .models import AdvUser

# class RegisterUserForm
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError
from .apps import user_registered

# class SubRubricForm
from .models import SuperRubric, SubRubric


class ChangeUserInfoForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Адрес электронной почты')

    class Meta:
        model = AdvUser
        fields = ('username', 'email', 'first_name', 'last_name', 'send_messages')


class RegisterUserForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Адрес электронной почты')
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput,
                                help_text=password_validation.password_validators_help_text_html())
    password2 = forms.CharField(label='Пароль (повторно)', widget=forms.PasswordInput,
                                help_text='Введите тот же пароль ещё раз для проверки')

    def clean_password1(self):
        password1 = self.cleaned_data['password1']
        if password1:
            password_validation.validate_password(password1)
        return password1

    def clean(self):
        super().clean()
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        if password1 and password2 and password1 !=password2:
            errors = {'password2': ValidationError('Введенные пароли не совпадают', code='password_mismatch')}
            raise ValidationError(errors)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.is_active = False
        user.is_activated = False
        if commit:
            user.save()
        user_registered.send(RegisterUserForm, instance=user)
        return user

    class Meta:
        model = AdvUser
        fields = ('username', 'email', 'password1', 'password2', 'first_name', 'last_name', 'send_messages')


class SubRubricForm(forms.ModelForm):
    super_rubric = forms.ModelChoiceField(queryset=SuperRubric.objects.all(), empty_label=None, label='Надрубрики', required=True)

    class Meta:
        model = SubRubric
        fields = '__all__'

bboard/main/views.py
# D:\User\Documents\PycharmProjects\MoloshopBY\bboard\main\views.py

# def index()
from django.shortcuts import render

# def other_page()
from django.http import HttpResponse, Http404
from django.template import TemplateDoesNotExist
from django.template.loader import get_template

# class BBLoginView()
from django.contrib.auth.views import LoginView

# @login_required
from django.contrib.auth.decorators import login_required

# class BBLogoutView()
from django.contrib.auth.views import LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin

# class ChangeUserInfoView
from django.views.generic.edit import UpdateView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
from .models import AdvUser
from .forms import ChangeUserInfoForm

# class BBPasswordChangeView
from django.contrib.auth.views import PasswordChangeView

# RegisterUserView
from django.views.generic.edit import CreateView
from .forms import RegisterUserForm

# RegisterDoneView
from django.views.generic.base import TemplateView

# def user_activate
from django.core.signing import BadSignature
from .utilities import signer

# class DeleteUserView
from django.views.generic.edit import DeleteView
from django.contrib.auth import logout
from django.contrib import messages



def index(request):
    return render(request, 'main/index.html')


def other_page(request, page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404

    return HttpResponse(template.render(request=request))


class BBLoginView(LoginView):
    template_name = 'main/login.html'

@login_required
def profile(request):
    return render(request, 'main/profile.html')


class BBLogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'main/logout.html'

class ChangeUserInfoView (SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = AdvUser
    template_name = 'main/change_user_info.html'
    form_class = ChangeUserInfoForm
    success_url = reverse_lazy('main:profile')
    success_message = 'Данные пользователя изменены'

    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super() .setup(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


class BBPasswordChangeView(SuccessMessageMixin, LoginRequiredMixin, PasswordChangeView):
    template_name = 'main/password_change.html'
    success_url = reverse_lazy('main:profile')
    success_message = 'Пароль пользователя изменен'


class RegisterUserView(CreateView):
    model = AdvUser
    template_name = 'main/register_user.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('main:register_done')


class RegisterDoneView(TemplateView):
    template_name = 'main/register_done.html'


def user_activate(request, sign):
    try:
        username = signer.unsign(sign)
    except BadSignature:
        return render(request, 'main/bad_signature.html')
    user = get_object_or_404(AdvUser, username=username)
    if user.is_activated:
        template = 'main/activation_done.html'
        user.is_active = True
        user.is_activated = True
        user.save()
    return render(request, template)


class DeleteUserView(LoginRequiredMixin, DeleteView):
    model = AdvUser
    template_name = 'main/delete_user.html'
    success_url = reverse_lazy('main:index')

    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super(DeleteUserView, self).setup(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        logout(request)
        messages.add_message(request, messages.SUCCESS, 'Пользователь удален')
        return super(DeleteUserView, self).post(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)

def by_rubric(request, pk):
    pass

bboard/main/templates/main/about.html
{% extends "layout/basic.html" %}
{% block title %} О сайте {% endblock %}

{% block content %}
<h2>О сайте</h2>
<p>Сайт для публикации объявлений о продаже, разбитых на рубрики</p>
<p>Все прова принадлежат Мне</p>
{% endblock %}

bboard/main/templates/main/activation_done.html
{% extends "layout/basic.html" %}

{% block title %} Активация выполнена {% endblock %}

{% block content %}
<h2>Активация</h2>
<p>Пользователь с таким именем успешно активирован</p>
<p><a href="{% url 'main:login' %}">Войти на сайт</a></p>
{% endblock %}

bboard/main/templates/main/bad_signature.html
{% extends "layout/basic.html" %}

{% block title %} Ошибка при ативации {% endblock %}

{% block content %}
<h2>Неудачная активация</h2>
<p>Активация пользователя с таким именем прошла неудачно</p>
<p><a href="{% url 'main:register' %}">Зарегестрироваться повторно</a></p>
{% endblock %}

bboard/main/templates/main/change_user_info.html
{% extends "layout/basic.html" %}
{% load bootstrap4 %}

{% block title %} Правка личных данных  {% endblock %}

{% block content %}
<h2>Правка личных данных поль зователя {{user.username}}</h2>
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% buttons submit='Сохранить' %} {% endbuttons %}
</form>
{% endblock %}

bboard/main/templates/main/delete_user.html
{% extends "layout/basic.html" %}
{% load bootstrap4 %}

{% block title %} Удаление пользователя {% endblock %}

{% block content %}
<h2>Удаление пользователя {{ object.username }}</h2>
<form method="post">
    {% csrf_token %}
    {% buttons submit='Удалить' %} {% endbuttons %}
</form>
{% endblock %}

bboard/main/templates/main/index.html
{% extends "layout/basic.html" %}
{% block content %}
<h2>Последние 10 объявлений</h2>
{% endblock %}

bboard/main/templates/main/login.html
{% extends "layout/basic.html" %}
{% load bootstrap4 %}

{% block title %} Вход {% endblock %}

{% block content %}
<h2>Вход</h2>
{% if user.is_authenticated %}
<p>Вы уже выполнили вход</p>
{% else %}
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    <input type="hidden" name="next" value="{{next}}">
    {% buttons submit='Войти' %} {% endbuttons %}
</form>
{% endif %}
{% endblock %}

bboard/main/templates/main/logout.html
{% extends "layout/basic.html" %}

{% block title %} Выход {% endblock %}

{% block content %}
<h2>Выход</h2>
<p>Вы успешно вышли с сайта</p>
{% endblock %}

bboard/main/templates/main/password_change.html
{% extends "layout/basic.html" %}
{% load bootstrap4 %}

{% block title %} Смена пароля {% endblock %}

{% block content %}
<h2>Смена пароля пользователя {{user.username}}</h2>
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% buttons submit='Сменить пароль' %} {% endbuttons %}
</form>
{% endblock %}

bboard/main/templates/main/profile.html
{% extends "layout/basic.html" %}

{% block title %} Профиль пользователя {% endblock %}

{% block content %}
<h2>Профиль пользователя {{ user.username }}</h2>

{% if user.first_name and user.last_name %}
<p>Здравствуйте, {{ user.first_name }} {{ user.last_name }}</p>
{% else %}
<p>Здраствуйте!</p>
{% endif %}
<h3>Ваши объявления</h3>
{% endblock %}

bboard/main/templates/main/register_done.html
{% extends "layout/basic.html" %}

{% block title %} Регистрация завершена {% endblock %}

{% block content %}
<h2>Регистрация</h2>
<p>Регистрация пользователя завершена</p>
<p>На адрес электронной почты, указанный пользователем, выслано письмо для активации.</p>
{% endblock %}

bboard/main/templates/main/register_user.html
{% extends "layout/basic.html" %}
{% load bootstrap4 %}

{% block title %} Регистрация {% endblock %}

{% block content %}
<h2>Регистрация нового пользователя</h2>
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% buttons submit='Зарегистрироваться' %} {% endbuttons %}
</form>
{% endblock %}

bboard/main/templates/main/user_is_activated.html
{% extends "layout/basic.html" %}

{% block title %} Пользователь уже активирован {% endblock %}

{% block content %}
<h2>Активация</h2>
<p>Пользователь с таким именем был активирован ранее. </p>
<p><a href="{% url 'main:login' %}">Войти на сайт</a></p>
{% endblock %}